name: check and publish release Python tarball to PyPi

on: workflow_dispatch

jobs:
  build-job:
    name: Check and publish snapshot tarball to PyPi
    uses: th2-net/.github/.github/workflows/compound-python.yml@main
    with:
      release-type: release
      style-check-enabled: false
      test-enabled: false
      create-tag: true

    secrets:
      pypi-password: ${{ secrets.PYPI_PASSWORD }}